services:
  personal_blog:
    container_name: personal_blog
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./personal_blog:/personal_blog
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env